### ISSUE TITLE
Compile on windows

### ISSUE THREAD

**Issue by clebertsuconic** [check-leak/check-leak#3]
I tried compiling the library in windows and I had a few issues. 

I wanted to use gcc to avoid depending on visual studio.  But it was a challenge.  The compiler would not identify __int64 and it would fail right away. 

I would appreciate help on this task.

**Comment by clebertsuconic** [comment]
@gastaldi the build is fixed...  yay... tests are compiling.


I saw a couple of options to get access to the DLL so it can be part of the release. In your opinion what is the best way?


I mean, I don't want to have every commit pushing a new DLL commit on the repo. Perhaps there's a way to configure an action that will push a commit?

**Comment by gastaldi** [comment]
How about having a separate repository publishing the DLLs using different classifiers?

**Comment by clebertsuconic** [comment]
@gastaldi are you strong opinionated about it? I would prefer to keep it simple. single jar it easy enough.

**Comment by clebertsuconic** [comment]
@gastaldi I will close this issue and open a new one.. provide .dll on the distribution for windows.
